import test from "node:test";
import assert from "node:assert/strict";
import {ACTIVE_SESSION_KEY,SESSION_HISTORY_KEY,deleteStoredSession,deriveTimerState,nextDeadline,readActiveSessionResult,readSessionHistoryResult,remainingSeconds} from "../lib/session.ts";

function withStorage(seed,run){const values=new Map(Object.entries(seed));globalThis.localStorage={getItem:key=>values.get(key)??null,setItem:(key,value)=>values.set(key,value),removeItem:key=>values.delete(key)};try{return run(values)}finally{delete globalThis.localStorage}}
function session(overrides={}){return {version:3,id:"session-1",worker:"Amina Njoroge",site:"Pump station 4",task:"Inspect motor controls",safetyNotes:"",emergencyName:"David Mwangi",emergencyPhone:"+254700000000",emergencyContactConfirmed:true,intervalMinutes:15,expectedDurationMinutes:120,startedAt:"2026-08-14T10:00:00.000Z",expectedEndAt:"2026-08-14T12:00:00.000Z",deadlineAt:"2026-08-14T10:15:00.000Z",phase:"active",checkIns:[],missedCheckIns:0,notificationPermission:"prompt",...overrides}}

test("remainingSeconds uses an absolute deadline",()=>{assert.equal(remainingSeconds("2026-08-14T10:01:00.000Z",Date.parse("2026-08-14T10:00:10.000Z")),50)});
test("remainingSeconds never becomes negative",()=>{assert.equal(remainingSeconds("2026-08-14T10:00:00.000Z",Date.parse("2026-08-14T10:00:01.000Z")),0)});
test("nextDeadline adds the selected interval",()=>{assert.equal(nextDeadline(30,Date.parse("2026-08-14T10:00:00.000Z")),"2026-08-14T10:30:00.000Z")});
test("timer states do not use red before overdue",()=>{const active=session();assert.equal(deriveTimerState(active,Date.parse("2026-08-14T10:05:00.000Z")),"normal");assert.equal(deriveTimerState(active,Date.parse("2026-08-14T10:12:30.000Z")),"approaching");assert.equal(deriveTimerState(active,Date.parse("2026-08-14T10:14:30.000Z")),"due-soon");assert.equal(deriveTimerState(session({phase:"grace",graceDeadlineAt:"2026-08-14T10:17:00.000Z"}),Date.parse("2026-08-14T10:16:00.000Z")),"grace");assert.equal(deriveTimerState(session({phase:"overdue"}),Date.parse("2026-08-14T10:18:00.000Z")),"overdue")});
test("version 2 active sessions migrate without losing core fields",()=>withStorage({[ACTIVE_SESSION_KEY]:JSON.stringify({version:2,id:"legacy",worker:"Legacy Worker",site:"Roof A",emergencyName:"Contact",emergencyPhone:"123",intervalMinutes:30,startedAt:"2026-08-14T10:00:00.000Z",deadlineAt:"2026-08-14T10:30:00.000Z",phase:"active",checkIns:[]})},values=>{const result=readActiveSessionResult(Date.parse("2026-08-14T10:05:00.000Z"));assert.equal(result.status,"valid");assert.equal(result.session.worker,"Legacy Worker");assert.equal(result.session.version,3);assert.equal(JSON.parse(values.get(ACTIVE_SESSION_KEY)).version,3)}));
test("corrupt stored sessions are surfaced for recovery",()=>withStorage({[ACTIVE_SESSION_KEY]:"{broken"},()=>assert.equal(readActiveSessionResult().status,"corrupt")));
test("old valid sessions are marked stale instead of silently resumed",()=>withStorage({[ACTIVE_SESSION_KEY]:JSON.stringify(session())},()=>assert.equal(readActiveSessionResult(Date.parse("2026-08-24T10:00:00.000Z")).status,"stale")));
test("corrupt local history is reported without overwriting it",()=>withStorage({[SESSION_HISTORY_KEY]:"{broken"},values=>{const result=readSessionHistoryResult();assert.equal(result.status,"corrupt");assert.equal(values.get(SESSION_HISTORY_KEY),"{broken")}));
test("a stored session can be deleted without affecting other records",()=>{const first={...session(),endedAt:"2026-08-14T11:00:00.000Z",outcome:"completed"};const second={...session({id:"session-2"}),endedAt:"2026-08-14T11:30:00.000Z",outcome:"completed"};withStorage({[SESSION_HISTORY_KEY]:JSON.stringify([first,second])},values=>{assert.equal(deleteStoredSession("session-1"),true);const remaining=JSON.parse(values.get(SESSION_HISTORY_KEY));assert.deepEqual(remaining.map(item=>item.id),["session-2"])})});
test("unavailable local storage is surfaced",()=>{globalThis.localStorage={getItem(){throw new Error("blocked")},setItem(){throw new Error("blocked")},removeItem(){throw new Error("blocked")}};try{assert.equal(readSessionHistoryResult().status,"unavailable")}finally{delete globalThis.localStorage}});