import {chromium} from "playwright";
import fs from "node:fs/promises";
import path from "node:path";
const base="http://localhost:3007/checkin";const out=path.join(process.cwd(),"deliverables","checkin");await fs.mkdir(out,{recursive:true});
const browser=await chromium.launch({headless:true,executablePath:"C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe"});const checks=[];const errors=[];const ok=(name,value,detail="")=>{checks.push({name,ok:Boolean(value),detail});if(!value)throw new Error(`${name}: ${detail}`)};
async function pageWith(context){const page=await context.newPage();page.on("console",m=>{if(m.type()==="error")errors.push(`console: ${m.text()}`)});page.on("pageerror",e=>errors.push(`page: ${e.message}`));page.on("dialog",d=>d.accept());await page.goto(base,{waitUntil:"domcontentloaded"});await page.getByRole("heading",{name:"Prepare the safety session."}).waitFor();return page}
const context=await browser.newContext({viewport:{width:360,height:800},permissions:[]});const page=await pageWith(context);
const sizing=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,client:document.documentElement.clientWidth,minFont:Math.min(...[...document.querySelectorAll("label,p,button,input,select,textarea")].map(e=>parseFloat(getComputedStyle(e).fontSize)).filter(Boolean))}));ok("360px has no horizontal overflow",sizing.scroll===sizing.client,JSON.stringify(sizing));ok("body text remains readable",sizing.minFont>=10,`${sizing.minFont}px minimum supporting text`);
await page.getByRole("button",{name:/test precise location/i}).click();await page.getByText("Permission denied").waitFor();ok("denied GPS has clear status",true);
await page.getByLabel("Worker name *").fill("Amina Njoroge");await page.getByLabel("Site or work location *").fill("Remote pump station 4");await page.getByLabel("Work activity or task *").fill("Inspect motor controls and isolation points");await page.getByLabel("Expected session duration").selectOption("120");await page.getByLabel("Check-in interval").selectOption("5");await page.getByLabel("Optional safety notes").fill("Arc-rated PPE required; radio check before entry.");await page.getByLabel("Contact name *").fill("David Mwangi");await page.getByLabel("Contact phone number *").fill("+254700000000");await page.getByRole("button",{name:"Review safety session"}).click();await page.getByRole("heading",{name:"Confirm before work begins."}).waitFor();ok("review includes GPS and escalation",await page.getByText(/2-minute on-device grace period/i).isVisible());const start=page.getByRole("button",{name:/start safety session/i});ok("contact acknowledgement gates start",await start.isDisabled());await page.getByLabel(/I confirm my emergency contact/i).check();await start.click();await page.getByText("Session active").waitFor();
await page.screenshot({path:path.join(out,"active-mobile.png"),fullPage:true});const before=await page.locator("strong").first().textContent();const storedBefore=await page.evaluate(()=>JSON.parse(localStorage.getItem("ss_active_session_v2")));await page.reload({waitUntil:"domcontentloaded"});await page.getByText("Session active").waitFor();const storedAfter=await page.evaluate(()=>JSON.parse(localStorage.getItem("ss_active_session_v2")));ok("refresh restores same active session",storedAfter.id===storedBefore.id);ok("refresh preserves absolute deadline",storedAfter.deadlineAt===storedBefore.deadlineAt,`${storedBefore.deadlineAt} -> ${storedAfter.deadlineAt}`);ok("timer remains visible after refresh",Boolean(before));
await page.evaluate(()=>{const s=JSON.parse(localStorage.getItem("ss_active_session_v2"));s.phase="grace";s.deadlineAt=new Date(Date.now()-1000).toISOString();s.graceDeadlineAt=new Date(Date.now()+90000).toISOString();s.missedCheckIns=1;localStorage.setItem("ss_active_session_v2",JSON.stringify(s))});await page.reload({waitUntil:"domcontentloaded"});await page.getByText("Grace period",{exact:true}).waitFor();ok("grace screen states no notification was sent",await page.getByText(/No contact or emergency service has been notified/i).first().isVisible());await page.screenshot({path:path.join(out,"grace-mobile.png"),fullPage:true});
await page.evaluate(()=>{const s=JSON.parse(localStorage.getItem("ss_active_session_v2"));s.phase="overdue";s.graceDeadlineAt=new Date(Date.now()-1000).toISOString();localStorage.setItem("ss_active_session_v2",JSON.stringify(s))});await page.reload({waitUntil:"domcontentloaded"});await page.getByRole("heading",{name:"Your session is overdue."}).waitFor();ok("overdue shows contact preview",await page.getByText(/Emergency-contact escalation preview/i).isVisible());await page.screenshot({path:path.join(out,"overdue-mobile.png"),fullPage:true});await page.getByRole("button",{name:/I’m safe/i}).click();await page.getByText("Session active").waitFor();ok("safe check-in clears overdue state",true);await page.getByRole("button",{name:"End session"}).click();await page.getByRole("heading",{name:"Session record complete."}).waitFor();ok("completion includes task",await page.getByText(/Inspect motor controls/i).first().isVisible());ok("completion includes GPS and missed metrics",await page.getByText("GPS captures",{exact:true}).isVisible()&&await page.getByText("Missed check-ins",{exact:true}).isVisible());await page.screenshot({path:path.join(out,"complete-mobile.png"),fullPage:true});
const unavailableContext=await browser.newContext({viewport:{width:390,height:844}});await unavailableContext.addInitScript(()=>Object.defineProperty(navigator,"geolocation",{configurable:true,value:undefined}));const unavailable=await pageWith(unavailableContext);await unavailable.getByRole("button",{name:/test precise location/i}).click();ok("unavailable geolocation is explained",await unavailable.getByText("Not supported on this device").first().isVisible());await unavailableContext.close();
const corruptContext=await browser.newContext({viewport:{width:390,height:844}});const corrupt=await corruptContext.newPage();await corrupt.goto(base);await corrupt.evaluate(()=>localStorage.setItem("ss_active_session_v2","{broken"));await corrupt.reload();await corrupt.getByRole("heading",{name:"Stored session data is damaged."}).waitFor();ok("corrupt data offers recovery",await corrupt.getByRole("button",{name:"Discard saved data"}).isVisible());await corruptContext.close();
const desktop=await browser.newContext({viewport:{width:1440,height:1000}});const desktopPage=await pageWith(desktop);await desktopPage.screenshot({path:path.join(out,"setup-desktop.png"),fullPage:true});ok("desktop setup renders",await desktopPage.getByText("Device readiness").isVisible());await desktop.close();await context.close();await browser.close();const report={checks,errors,allPassed:checks.every(c=>c.ok)&&errors.length===0};await fs.writeFile(path.join(out,"browser-verification.json"),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));if(!report.allPassed)process.exitCode=1;