-- DESIGN ONLY. Not applied to any database.
-- PostgreSQL-compatible multi-tenant schema for a future monitored service.
create extension if not exists pgcrypto;
create type member_role as enum ('worker','supervisor','organization_admin');
create type session_state as enum ('draft','ready','active','due_soon','grace','overdue','escalating','acknowledged','resolved','completed','cancelled','expired');
create table organizations(id uuid primary key default gen_random_uuid(),name text not null check(length(name) between 1 and 160),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),retention_days integer not null default 365 check(retention_days between 30 and 3650));
create table users(id uuid primary key,verified_email text not null,created_at timestamptz not null default now(),disabled_at timestamptz);
create table organization_memberships(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id),user_id uuid not null references users(id),role member_role not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,user_id));
create table workers(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id),user_id uuid references users(id),display_name text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),deleted_at timestamptz);
create table emergency_contacts(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id),worker_id uuid not null references workers(id),name text not null,phone_ciphertext bytea not null,phone_last_four text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),deleted_at timestamptz);
create table sites(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id),name text not null,timezone text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),deleted_at timestamptz);
create table escalation_policies(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id),name text not null,version integer not null,active boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,name,version));
create table escalation_steps(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id),policy_id uuid not null references escalation_policies(id),position integer not null check(position>0),delay_seconds integer not null check(delay_seconds>=0),channel text not null check(channel in ('sms','voice','email','push','manual')),target_type text not null,created_at timestamptz not null default now(),unique(policy_id,position));
create table lone_work_sessions(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id),worker_id uuid not null references workers(id),site_id uuid references sites(id),emergency_contact_id uuid references emergency_contacts(id),policy_id uuid references escalation_policies(id),created_by uuid not null references users(id),task text not null,safety_notes_ciphertext bytea,state session_state not null default 'draft',interval_seconds integer not null check(interval_seconds between 60 and 86400),expected_duration_seconds integer not null check(expected_duration_seconds between 60 and 604800),started_at timestamptz,expected_end_at timestamptz,next_check_in_at timestamptz,grace_deadline_at timestamptz,overdue_at timestamptz,completed_at timestamptz,cancelled_at timestamptz,resolved_at timestamptz,resolution text,version integer not null default 1,retain_until timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table check_ins(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id),session_id uuid not null references lone_work_sessions(id),worker_id uuid not null references workers(id),idempotency_key text not null,client_observed_at timestamptz,received_at timestamptz not null default now(),acknowledged boolean not null default true,unique(organization_id,idempotency_key));
create table location_samples(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id),session_id uuid not null references lone_work_sessions(id),check_in_id uuid references check_ins(id),latitude_ciphertext bytea not null,longitude_ciphertext bytea not null,accuracy_meters numeric(10,2),captured_at timestamptz not null,received_at timestamptz not null default now(),retain_until timestamptz);
create table session_events(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id),session_id uuid not null references lone_work_sessions(id),actor_user_id uuid references users(id),event_type text not null,from_state session_state,to_state session_state,server_at timestamptz not null default now(),idempotency_key text,metadata jsonb not null default '{}',unique(organization_id,idempotency_key));
create table escalation_attempts(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id),session_id uuid not null references lone_work_sessions(id),step_id uuid not null references escalation_steps(id),idempotency_key text not null,attempt_number integer not null check(attempt_number>0),status text not null,scheduled_at timestamptz not null,started_at timestamptz,finished_at timestamptz,next_retry_at timestamptz,last_error_code text,created_at timestamptz not null default now(),unique(organization_id,idempotency_key));
create table notifications(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id),attempt_id uuid not null references escalation_attempts(id),provider text not null,provider_message_id text,status text not null,accepted_at timestamptz,delivered_at timestamptz,failed_at timestamptz,provider_response_redacted jsonb not null default '{}',created_at timestamptz not null default now(),unique(provider,provider_message_id));
create table supervisor_acknowledgements(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id),session_id uuid not null references lone_work_sessions(id),supervisor_user_id uuid not null references users(id),acknowledged_at timestamptz not null default now(),note text);
create table incident_resolutions(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id),session_id uuid not null references lone_work_sessions(id),resolved_by uuid not null references users(id),resolution_code text not null,summary text,created_at timestamptz not null default now());
create table audit_logs(id uuid primary key default gen_random_uuid(),organization_id uuid references organizations(id),actor_user_id uuid references users(id),action text not null,target_type text not null,target_id uuid,outcome text not null,request_id text,ip_hash text,metadata jsonb not null default '{}',server_at timestamptz not null default now());
create table data_export_requests(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id),requested_by uuid not null references users(id),status text not null,created_at timestamptz not null default now(),completed_at timestamptz,expires_at timestamptz);
create table account_deletion_requests(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id),requested_by uuid not null references users(id),status text not null,created_at timestamptz not null default now(),reviewed_at timestamptz,completed_at timestamptz);
create index sessions_org_state_deadline_idx on lone_work_sessions(organization_id,state,next_check_in_at);
create index sessions_org_worker_created_idx on lone_work_sessions(organization_id,worker_id,created_at desc);
create index sessions_org_site_created_idx on lone_work_sessions(organization_id,site_id,created_at desc);
create index events_org_session_time_idx on session_events(organization_id,session_id,server_at);
create index attempts_status_schedule_idx on escalation_attempts(status,scheduled_at);
create index audit_org_time_idx on audit_logs(organization_id,server_at desc);
-- Enforce organization membership and row-level security in provider-specific migrations.
-- Safety and audit records intentionally have no destructive ON DELETE CASCADE.
