"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {AlertTriangle,Check,ChevronDown,Clock3,Download,FileWarning,HardDrive,MapPin,Phone,Radio,RefreshCw,Search,ShieldCheck,Trash2,UserRound,Users} from "lucide-react";
import {SessionHistoryReadResult,StoredSession,deleteStoredSession,readSessionHistoryResult} from "@/lib/session";
import styles from "./dashboard.module.css";
import {SiteFooter} from "@/components/site-footer";

type Status="active"|"safe"|"due-soon"|"overdue"|"offline";
type Worker={id:string;name:string;initials:string;role:string;site:string;location:string;status:Status;lastCheckIn:string;nextCheckIn:string;interval:string;checkIns:number;hasContact:boolean;overdueBy?:string;contact?:string;escalation?:string};
const sampleWorkers:Worker[]=[
 {id:"SS-1042",name:"Marcus Webb",initials:"MW",role:"Electrical technician",site:"Northbank Energy",location:"Plant room B · Level 2",status:"active",lastCheckIn:"8 min ago",nextCheckIn:"in 22 min",interval:"30 min",checkIns:3,hasContact:true},
 {id:"SS-0971",name:"Sarah Okafor",initials:"SO",role:"HVAC specialist",site:"Meridian Tower",location:"Rooftop unit · Zone A",status:"overdue",lastCheckIn:"52 min ago",nextCheckIn:"10:24",interval:"30 min",checkIns:2,hasContact:true,overdueBy:"22 min",contact:"Ibrahim Okafor · +254 700 555 018",escalation:"Grace period ended · supervisor review"},
 {id:"SS-1108",name:"Dean Mitchell",initials:"DM",role:"Mechanical engineer",site:"Civic Waterworks",location:"Boiler room · Basement 1",status:"safe",lastCheckIn:"4 min ago",nextCheckIn:"in 26 min",interval:"30 min",checkIns:5,hasContact:true},
 {id:"SS-0884",name:"Priya Nambiar",initials:"PN",role:"Safety technician",site:"North Grid",location:"Substation 3B",status:"due-soon",lastCheckIn:"27 min ago",nextCheckIn:"in 3 min",interval:"30 min",checkIns:4,hasContact:true},
 {id:"SS-1024",name:"Jon Bell",initials:"JB",role:"Facilities officer",site:"Meridian Tower",location:"East service wing",status:"offline",lastCheckIn:"Shift ended",nextCheckIn:"—",interval:"30 min",checkIns:6,hasContact:false},
 {id:"SS-1137",name:"Elena Torres",initials:"ET",role:"Pump technician",site:"West Pump Station",location:"Pump hall · Bay 2",status:"active",lastCheckIn:"11 min ago",nextCheckIn:"in 19 min",interval:"30 min",checkIns:2,hasContact:true}
];
const statusLabels:Record<Status,string>={active:"Active",safe:"Safe", "due-soon":"Due soon",overdue:"Overdue",offline:"Offline"};
const filters:["all"|Status,string][]= [["all","All"],["active","Active"],["safe","Safe"],["due-soon","Due soon"],["overdue","Overdue"],["offline","Offline"]];
function relativeDuration(start:string,end:string){const minutes=Math.max(0,Math.round((Date.parse(end)-Date.parse(start))/60000));if(minutes<60)return `${minutes} min`;const hours=Math.floor(minutes/60);const remainder=minutes%60;return remainder?`${hours} hr ${remainder} min`:`${hours} hr`;}
function gpsCount(session:StoredSession){return session.checkIns.filter(item=>item.location).length+(session.initialLocation?1:0)}
function formatDate(value:string){return new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(new Date(value))}
function buildReport(session:StoredSession){return ["SAFESIGNAL SESSION RECORD",`Session: ${session.id}`,`Worker: ${session.worker}`,`Site: ${session.site}`,`Task: ${session.task}`,`Started: ${formatDate(session.startedAt)}`,`Ended: ${formatDate(session.endedAt)}`,`Duration: ${relativeDuration(session.startedAt,session.endedAt)}`,`Check-ins: ${session.checkIns.length}`,`GPS captures: ${gpsCount(session)}`,`Missed check-ins: ${session.missedCheckIns}`,`Outcome: ${session.outcome}`,"No contact or emergency service was notified by this on-device preview."].join("\n")}
function downloadRecord(session:StoredSession){const url=URL.createObjectURL(new Blob([buildReport(session)],{type:"text/plain;charset=utf-8"}));const link=document.createElement("a");link.href=url;link.download=`safesignal-${session.id}.txt`;link.click();URL.revokeObjectURL(url)}
function StatusBadge({status}:{status:Status}){return <span className={`${styles.status} ${styles[status]}`}><i/>{statusLabels[status]}</span>}
function WorkerCard({worker}:{worker:Worker}){return <article className={`${styles.workerCard} ${worker.status===`overdue`?styles.workerOverdue:""}`}><div className={styles.identity}><span>{worker.initials}</span><div><b>{worker.name}</b><small>{worker.role}</small></div></div><div className={styles.location}><b>{worker.site}</b><small><MapPin/>{worker.location}</small></div><div className={styles.workerStatus}><StatusBadge status={worker.status}/>{worker.status==="overdue"?<strong>{worker.overdueBy} overdue</strong>:<small>Next {worker.nextCheckIn}</small>}</div><dl className={styles.workerFacts}><div><dt>Last check-in</dt><dd>{worker.lastCheckIn}</dd></div><div><dt>Interval</dt><dd>{worker.interval}</dd></div><div><dt>Check-ins</dt><dd>{worker.checkIns}</dd></div><div><dt>Emergency contact</dt><dd>{worker.hasContact?<><Check/>Available</>:"Not provided"}</dd></div></dl></article>}
function IncidentPanel({worker}:{worker:Worker}){return <aside className={styles.incident} aria-labelledby="incident-title"><header><span><AlertTriangle/></span><div><small>Sample overdue incident</small><h2 id="incident-title">Supervisor attention required</h2></div><StatusBadge status="overdue"/></header><div className={styles.incidentPerson}><span>{worker.initials}</span><div><b>{worker.name}</b><small>{worker.role} · {worker.id}</small></div></div><dl><div><dt>Site</dt><dd>{worker.site}</dd></div><div><dt>Last known location</dt><dd>{worker.location}</dd></div><div><dt>Last check-in</dt><dd>{worker.lastCheckIn}</dd></div><div><dt>Time overdue</dt><dd>{worker.overdueBy}</dd></div><div><dt>Emergency contact</dt><dd>{worker.contact}</dd></div><div><dt>Escalation stage</dt><dd>{worker.escalation}</dd></div></dl><div className={styles.demoNotice}><FileWarning/><p><b>Illustrative controls only.</b> This preview cannot message, call, dispatch, or acknowledge an incident.</p></div><div className={styles.demoActions}><button disabled title="Demo action — calling is not connected"><Phone/>Demo action: call contact</button><button disabled title="Demo action — incident workflows are not connected"><Check/>Demo action: acknowledge</button></div></aside>}
function LocalSessionCard({session,open,onToggle,onDelete}:{session:StoredSession;open:boolean;onToggle:()=>void;onDelete:()=>void}){return <article className={styles.localCard}><div className={styles.localMain}><div className={styles.localIdentity}><span><UserRound/></span><div><b>{session.worker}</b><small>{session.site}</small></div></div><dl><div><dt>Started</dt><dd>{formatDate(session.startedAt)}</dd></div><div><dt>Duration</dt><dd>{relativeDuration(session.startedAt,session.endedAt)}</dd></div><div><dt>Check-ins</dt><dd>{session.checkIns.length}</dd></div><div><dt>GPS</dt><dd>{gpsCount(session)}</dd></div></dl><div className={styles.localActions}><button onClick={onToggle} aria-expanded={open}><ChevronDown/> {open?"Hide details":"View details"}</button><button onClick={()=>downloadRecord(session)}><Download/>Export record</button><button className={styles.delete} onClick={onDelete}><Trash2/>Delete</button></div></div>{open?<div className={styles.localDetails}><div><span>Task</span><b>{session.task||"Not recorded"}</b></div><div><span>Outcome</span><b>{session.outcome.replaceAll("-"," ")}</b></div><div><span>Ended</span><b>{formatDate(session.endedAt)}</b></div><div><span>Missed check-ins</span><b>{session.missedCheckIns}</b></div>{session.safetyNotes?<p><b>Safety notes</b>{session.safetyNotes}</p>:null}</div>:null}</article>}
export default function DashboardPage(){
 const[query,setQuery]=useState("");const[filter,setFilter]=useState<"all"|Status>("all");const[now,setNow]=useState<Date|null>(null);const[lastRefreshed,setLastRefreshed]=useState<Date|null>(null);const[history,setHistory]=useState<SessionHistoryReadResult>({status:"empty",sessions:[]});const[openSession,setOpenSession]=useState<string|null>(null);
 const refresh=()=>{const result=readSessionHistoryResult();setHistory(result);const current=new Date();setNow(current);setLastRefreshed(current)};
 useEffect(()=>{queueMicrotask(refresh);const id=window.setInterval(()=>setNow(new Date()),60_000);return()=>clearInterval(id)},[]);
 const shown=useMemo(()=>{const term=query.trim().toLowerCase();return sampleWorkers.filter(worker=>(filter==="all"||worker.status===filter)&&(!term||`${worker.name} ${worker.role} ${worker.site}`.toLowerCase().includes(term)))},[query,filter]);
 const counts=useMemo(()=>Object.fromEntries(["active","safe","due-soon","overdue","offline"].map(status=>[status,sampleWorkers.filter(worker=>worker.status===status).length])) as Record<Status,number>,[]);
 const overdueWorker=sampleWorkers.find(worker=>worker.status==="overdue")!;
 const remove=(session:StoredSession)=>{if(!window.confirm(`Delete the local session record for ${session.worker}? This cannot be undone.`))return;if(deleteStoredSession(session.id))refresh();else setHistory({status:"unavailable",sessions:history.sessions})};
 return <><a className={styles.skip} href="#dashboard-content">Skip to dashboard</a><main id="dashboard-content" className={styles.page}><header className={styles.header}><Link href="/" className={styles.brand}><ShieldCheck/>Safe<span>Signal</span></Link><div className={styles.headerActions}><span className={styles.preview}><i/>Sample supervisor preview</span><Link href="/checkin"><Radio/>Start personal check-in</Link></div></header><div className={styles.container}>
 <section className={styles.hero}><div><small>Supervisor dashboard</small><h1>Team safety overview</h1><p>Prioritise overdue workers, then review routine check-in status. Team data below is illustrative.</p></div><div className={styles.time}><b>{now?new Intl.DateTimeFormat(undefined,{dateStyle:"full"}).format(now):"Loading date…"}</b><strong>{now?new Intl.DateTimeFormat(undefined,{hour:"2-digit",minute:"2-digit",timeZoneName:"short"}).format(now):"--:--"}</strong><span><RefreshCw/>Last refreshed {lastRefreshed?new Intl.DateTimeFormat(undefined,{hour:"2-digit",minute:"2-digit",second:"2-digit"}).format(lastRefreshed):"—"}</span><button onClick={refresh}><RefreshCw/>Refresh local records</button></div></section>
 <section className={styles.summary} aria-label="Sample worker summary"><SummaryCard label="Total workers" value={sampleWorkers.length} icon={<Users/>}/><SummaryCard label="Active sessions" value={counts.active} tone="blue" icon={<Radio/>}/><SummaryCard label="Safe / checked in" value={counts.safe} tone="green" icon={<ShieldCheck/>}/><SummaryCard label="Due soon" value={counts["due-soon"]} tone="orange" icon={<Clock3/>}/><SummaryCard label="Overdue" value={counts.overdue} tone="red" icon={<AlertTriangle/>}/><SummaryCard label="Offline" value={counts.offline} icon={<UserRound/>}/><SummaryCard label="Local records" value={history.sessions.length} icon={<HardDrive/>}/></section>
 <IncidentPanel worker={overdueWorker}/>
 <section className={styles.workers} aria-labelledby="workers-title"><div className={styles.sectionHead}><div><small>Sample team data</small><h2 id="workers-title">Worker status</h2><p>These workers do not represent live people or connected accounts.</p></div><label className={styles.search}><Search/><span className={styles.srOnly}>Search sample workers</span><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search worker, role, or site"/></label></div><div className={styles.filters} role="group" aria-label="Filter workers">{filters.map(([value,label])=><button key={value} className={filter===value?styles.filterActive:""} onClick={()=>setFilter(value)} aria-pressed={filter===value}>{label}<span>{value==="all"?sampleWorkers.length:counts[value]}</span></button>)}</div>{shown.length?<div className={styles.workerList}><div className={styles.workerColumns}><span>Worker</span><span>Site</span><span>Status</span><span>Session details</span></div>{shown.map(worker=><WorkerCard key={worker.id} worker={worker}/>)}</div>:<div className={styles.empty}><Search/><h3>No workers found</h3><p>{query?"No sample workers match this search. Clear the search or choose another status.":"No sample workers match this status filter."}</p><button onClick={()=>{setQuery("");setFilter("all")}}>Clear filters</button></div>}</section>
 <section className={styles.local} aria-labelledby="local-title"><div className={styles.sectionHead}><div><small>Real records · this device only</small><h2 id="local-title">Local session history</h2><p>Completed personal check-ins stored in this browser. These records are never mixed with the sample team.</p></div><span className={styles.storageState} data-state={history.status}><HardDrive/>{history.status==="ok"?`${history.sessions.length} stored`:history.status==="empty"?"No saved sessions":history.status==="corrupt"?"Some data is corrupted":"Storage unavailable"}</span></div>{history.status==="unavailable"?<div className={styles.errorState}><FileWarning/><div><h3>Browser storage is unavailable</h3><p>SafeSignal cannot read, export, or delete local history in this browser context.</p></div><button onClick={refresh}>Try again</button></div>:null}{history.status==="corrupt"?<div className={styles.errorState}><FileWarning/><div><h3>Some local history could not be read</h3><p>Valid records are shown below. Corrupted entries were left untouched to avoid accidental data loss.</p></div></div>:null}{history.status!=="unavailable"&&!history.sessions.length?<div className={styles.empty}><HardDrive/><h3>No saved sessions on this device</h3><p>Complete a personal check-in to create a local record.</p><Link href="/checkin">Start personal check-in</Link></div>:null}{history.sessions.length?<div className={styles.localList}>{history.sessions.map(session=><LocalSessionCard key={session.id} session={session} open={openSession===session.id} onToggle={()=>setOpenSession(value=>value===session.id?null:session.id)} onDelete={()=>remove(session)}/>)}</div>:null}<p className={styles.localNotice}>Local browser storage only. No cloud account, supervisor sync, SMS, calls, or emergency dispatch is connected.</p></section>
 </div></main><SiteFooter/></>}
function SummaryCard({label,value,icon,tone="neutral"}:{label:string;value:number;icon:React.ReactNode;tone?:"neutral"|"blue"|"green"|"orange"|"red"}){return <article className={styles.summaryCard} data-tone={tone}><div><span>{label}</span>{icon}</div><b>{String(value).padStart(2,"0")}</b></article>}